/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiCallback;
import com.moosyl.ApiClient;
import com.moosyl.ApiException;
import com.moosyl.ApiResponse;
import com.moosyl.Configuration;
import com.moosyl.Pair;
import com.moosyl.ProgressRequestBody;
import com.moosyl.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.moosyl.model.CheckoutSessionCreate;
import com.moosyl.model.CheckoutSessionCreateBody;
import com.moosyl.model.CheckoutSessionGet;
import com.moosyl.model.CheckoutSessionPayBody;
import com.moosyl.model.CheckoutSessionSelectMethodBody;
import com.moosyl.model.CheckoutSessionSwitchMethod;
import com.moosyl.model.PostCheckoutSessionPublicByIdPay200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CheckoutSessionApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CheckoutSessionApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CheckoutSessionApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getCheckoutSessionPublicById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCheckoutSessionPublicByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/checkout-session/public/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCheckoutSessionPublicByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getCheckoutSessionPublicById(Async)");
        }

        return getCheckoutSessionPublicByIdCall(id, _callback);

    }

    /**
     * Get public checkout session
     * Get checkout session details without an API key.
     * @param id  (required)
     * @return CheckoutSessionGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public CheckoutSessionGet getCheckoutSessionPublicById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<CheckoutSessionGet> localVarResp = getCheckoutSessionPublicByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get public checkout session
     * Get checkout session details without an API key.
     * @param id  (required)
     * @return ApiResponse&lt;CheckoutSessionGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CheckoutSessionGet> getCheckoutSessionPublicByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getCheckoutSessionPublicByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<CheckoutSessionGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get public checkout session (asynchronously)
     * Get checkout session details without an API key.
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCheckoutSessionPublicByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<CheckoutSessionGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCheckoutSessionPublicByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<CheckoutSessionGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postCheckoutSession
     * @param checkoutSessionCreateBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCheckoutSessionCall(@javax.annotation.Nonnull CheckoutSessionCreateBody checkoutSessionCreateBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = checkoutSessionCreateBody;

        // create path and map variables
        String localVarPath = "/checkout-session";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postCheckoutSessionValidateBeforeCall(@javax.annotation.Nonnull CheckoutSessionCreateBody checkoutSessionCreateBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'checkoutSessionCreateBody' is set
        if (checkoutSessionCreateBody == null) {
            throw new ApiException("Missing the required parameter 'checkoutSessionCreateBody' when calling postCheckoutSession(Async)");
        }

        return postCheckoutSessionCall(checkoutSessionCreateBody, _callback);

    }

    /**
     * Create checkout session
     * Create a hosted checkout session from paymentRequestId, or from transactionId (optionally creating the payment request when amount is provided).
     * @param checkoutSessionCreateBody  (required)
     * @return CheckoutSessionCreate
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public CheckoutSessionCreate postCheckoutSession(@javax.annotation.Nonnull CheckoutSessionCreateBody checkoutSessionCreateBody) throws ApiException {
        ApiResponse<CheckoutSessionCreate> localVarResp = postCheckoutSessionWithHttpInfo(checkoutSessionCreateBody);
        return localVarResp.getData();
    }

    /**
     * Create checkout session
     * Create a hosted checkout session from paymentRequestId, or from transactionId (optionally creating the payment request when amount is provided).
     * @param checkoutSessionCreateBody  (required)
     * @return ApiResponse&lt;CheckoutSessionCreate&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CheckoutSessionCreate> postCheckoutSessionWithHttpInfo(@javax.annotation.Nonnull CheckoutSessionCreateBody checkoutSessionCreateBody) throws ApiException {
        okhttp3.Call localVarCall = postCheckoutSessionValidateBeforeCall(checkoutSessionCreateBody, null);
        Type localVarReturnType = new TypeToken<CheckoutSessionCreate>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create checkout session (asynchronously)
     * Create a hosted checkout session from paymentRequestId, or from transactionId (optionally creating the payment request when amount is provided).
     * @param checkoutSessionCreateBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCheckoutSessionAsync(@javax.annotation.Nonnull CheckoutSessionCreateBody checkoutSessionCreateBody, final ApiCallback<CheckoutSessionCreate> _callback) throws ApiException {

        okhttp3.Call localVarCall = postCheckoutSessionValidateBeforeCall(checkoutSessionCreateBody, _callback);
        Type localVarReturnType = new TypeToken<CheckoutSessionCreate>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postCheckoutSessionPublicByIdPay
     * @param id  (required)
     * @param checkoutSessionPayBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCheckoutSessionPublicByIdPayCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionPayBody checkoutSessionPayBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = checkoutSessionPayBody;

        // create path and map variables
        String localVarPath = "/checkout-session/public/{id}/pay"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postCheckoutSessionPublicByIdPayValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionPayBody checkoutSessionPayBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling postCheckoutSessionPublicByIdPay(Async)");
        }

        // verify the required parameter 'checkoutSessionPayBody' is set
        if (checkoutSessionPayBody == null) {
            throw new ApiException("Missing the required parameter 'checkoutSessionPayBody' when calling postCheckoutSessionPublicByIdPay(Async)");
        }

        return postCheckoutSessionPublicByIdPayCall(id, checkoutSessionPayBody, _callback);

    }

    /**
     * Pay public checkout session
     * Create payment for a checkout session without requiring API key in the client.
     * @param id  (required)
     * @param checkoutSessionPayBody  (required)
     * @return PostCheckoutSessionPublicByIdPay200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public PostCheckoutSessionPublicByIdPay200Response postCheckoutSessionPublicByIdPay(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionPayBody checkoutSessionPayBody) throws ApiException {
        ApiResponse<PostCheckoutSessionPublicByIdPay200Response> localVarResp = postCheckoutSessionPublicByIdPayWithHttpInfo(id, checkoutSessionPayBody);
        return localVarResp.getData();
    }

    /**
     * Pay public checkout session
     * Create payment for a checkout session without requiring API key in the client.
     * @param id  (required)
     * @param checkoutSessionPayBody  (required)
     * @return ApiResponse&lt;PostCheckoutSessionPublicByIdPay200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostCheckoutSessionPublicByIdPay200Response> postCheckoutSessionPublicByIdPayWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionPayBody checkoutSessionPayBody) throws ApiException {
        okhttp3.Call localVarCall = postCheckoutSessionPublicByIdPayValidateBeforeCall(id, checkoutSessionPayBody, null);
        Type localVarReturnType = new TypeToken<PostCheckoutSessionPublicByIdPay200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Pay public checkout session (asynchronously)
     * Create payment for a checkout session without requiring API key in the client.
     * @param id  (required)
     * @param checkoutSessionPayBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCheckoutSessionPublicByIdPayAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionPayBody checkoutSessionPayBody, final ApiCallback<PostCheckoutSessionPublicByIdPay200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postCheckoutSessionPublicByIdPayValidateBeforeCall(id, checkoutSessionPayBody, _callback);
        Type localVarReturnType = new TypeToken<PostCheckoutSessionPublicByIdPay200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postCheckoutSessionPublicByIdSwitchMethod
     * @param id  (required)
     * @param checkoutSessionSelectMethodBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCheckoutSessionPublicByIdSwitchMethodCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionSelectMethodBody checkoutSessionSelectMethodBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = checkoutSessionSelectMethodBody;

        // create path and map variables
        String localVarPath = "/checkout-session/public/{id}/switch-method"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postCheckoutSessionPublicByIdSwitchMethodValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionSelectMethodBody checkoutSessionSelectMethodBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling postCheckoutSessionPublicByIdSwitchMethod(Async)");
        }

        // verify the required parameter 'checkoutSessionSelectMethodBody' is set
        if (checkoutSessionSelectMethodBody == null) {
            throw new ApiException("Missing the required parameter 'checkoutSessionSelectMethodBody' when calling postCheckoutSessionPublicByIdSwitchMethod(Async)");
        }

        return postCheckoutSessionPublicByIdSwitchMethodCall(id, checkoutSessionSelectMethodBody, _callback);

    }

    /**
     * Switch public checkout method
     * Switch checkout method and cancel the latest pending payment when present.
     * @param id  (required)
     * @param checkoutSessionSelectMethodBody  (required)
     * @return CheckoutSessionSwitchMethod
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public CheckoutSessionSwitchMethod postCheckoutSessionPublicByIdSwitchMethod(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionSelectMethodBody checkoutSessionSelectMethodBody) throws ApiException {
        ApiResponse<CheckoutSessionSwitchMethod> localVarResp = postCheckoutSessionPublicByIdSwitchMethodWithHttpInfo(id, checkoutSessionSelectMethodBody);
        return localVarResp.getData();
    }

    /**
     * Switch public checkout method
     * Switch checkout method and cancel the latest pending payment when present.
     * @param id  (required)
     * @param checkoutSessionSelectMethodBody  (required)
     * @return ApiResponse&lt;CheckoutSessionSwitchMethod&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CheckoutSessionSwitchMethod> postCheckoutSessionPublicByIdSwitchMethodWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionSelectMethodBody checkoutSessionSelectMethodBody) throws ApiException {
        okhttp3.Call localVarCall = postCheckoutSessionPublicByIdSwitchMethodValidateBeforeCall(id, checkoutSessionSelectMethodBody, null);
        Type localVarReturnType = new TypeToken<CheckoutSessionSwitchMethod>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Switch public checkout method (asynchronously)
     * Switch checkout method and cancel the latest pending payment when present.
     * @param id  (required)
     * @param checkoutSessionSelectMethodBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCheckoutSessionPublicByIdSwitchMethodAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull CheckoutSessionSelectMethodBody checkoutSessionSelectMethodBody, final ApiCallback<CheckoutSessionSwitchMethod> _callback) throws ApiException {

        okhttp3.Call localVarCall = postCheckoutSessionPublicByIdSwitchMethodValidateBeforeCall(id, checkoutSessionSelectMethodBody, _callback);
        Type localVarReturnType = new TypeToken<CheckoutSessionSwitchMethod>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
