/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiCallback;
import com.moosyl.ApiClient;
import com.moosyl.ApiException;
import com.moosyl.ApiResponse;
import com.moosyl.Configuration;
import com.moosyl.Pair;
import com.moosyl.ProgressRequestBody;
import com.moosyl.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.moosyl.model.DeleteConnectRevoke200Response;
import com.moosyl.model.DeleteConnectRevokeRequest;
import com.moosyl.model.PostConnectExchange200Response;
import com.moosyl.model.PostConnectExchangeRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ConnectApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ConnectApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ConnectApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deleteConnectRevoke
     * @param deleteConnectRevokeRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteConnectRevokeCall(@javax.annotation.Nonnull DeleteConnectRevokeRequest deleteConnectRevokeRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = deleteConnectRevokeRequest;

        // create path and map variables
        String localVarPath = "/connect/revoke";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deleteConnectRevokeValidateBeforeCall(@javax.annotation.Nonnull DeleteConnectRevokeRequest deleteConnectRevokeRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'deleteConnectRevokeRequest' is set
        if (deleteConnectRevokeRequest == null) {
            throw new ApiException("Missing the required parameter 'deleteConnectRevokeRequest' when calling deleteConnectRevoke(Async)");
        }

        return deleteConnectRevokeCall(deleteConnectRevokeRequest, _callback);

    }

    /**
     * Revoke a platform connection
     * Revoke a previously authorized connection between a platform and a Moosyl account.
     * @param deleteConnectRevokeRequest  (required)
     * @return DeleteConnectRevoke200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public DeleteConnectRevoke200Response deleteConnectRevoke(@javax.annotation.Nonnull DeleteConnectRevokeRequest deleteConnectRevokeRequest) throws ApiException {
        ApiResponse<DeleteConnectRevoke200Response> localVarResp = deleteConnectRevokeWithHttpInfo(deleteConnectRevokeRequest);
        return localVarResp.getData();
    }

    /**
     * Revoke a platform connection
     * Revoke a previously authorized connection between a platform and a Moosyl account.
     * @param deleteConnectRevokeRequest  (required)
     * @return ApiResponse&lt;DeleteConnectRevoke200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteConnectRevoke200Response> deleteConnectRevokeWithHttpInfo(@javax.annotation.Nonnull DeleteConnectRevokeRequest deleteConnectRevokeRequest) throws ApiException {
        okhttp3.Call localVarCall = deleteConnectRevokeValidateBeforeCall(deleteConnectRevokeRequest, null);
        Type localVarReturnType = new TypeToken<DeleteConnectRevoke200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Revoke a platform connection (asynchronously)
     * Revoke a previously authorized connection between a platform and a Moosyl account.
     * @param deleteConnectRevokeRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deleteConnectRevokeAsync(@javax.annotation.Nonnull DeleteConnectRevokeRequest deleteConnectRevokeRequest, final ApiCallback<DeleteConnectRevoke200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = deleteConnectRevokeValidateBeforeCall(deleteConnectRevokeRequest, _callback);
        Type localVarReturnType = new TypeToken<DeleteConnectRevoke200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postConnectExchange
     * @param postConnectExchangeRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postConnectExchangeCall(@javax.annotation.Nonnull PostConnectExchangeRequest postConnectExchangeRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = postConnectExchangeRequest;

        // create path and map variables
        String localVarPath = "/connect/exchange";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postConnectExchangeValidateBeforeCall(@javax.annotation.Nonnull PostConnectExchangeRequest postConnectExchangeRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'postConnectExchangeRequest' is set
        if (postConnectExchangeRequest == null) {
            throw new ApiException("Missing the required parameter 'postConnectExchangeRequest' when calling postConnectExchange(Async)");
        }

        return postConnectExchangeCall(postConnectExchangeRequest, _callback);

    }

    /**
     * Exchange authorization code for API credentials
     * Exchange a short-lived authorization code (obtained from the /connect flow) for the user&#39;s publishable key, secret key, and webhook secret. A webhook will be created using the provided endpoints.
     * @param postConnectExchangeRequest  (required)
     * @return PostConnectExchange200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public PostConnectExchange200Response postConnectExchange(@javax.annotation.Nonnull PostConnectExchangeRequest postConnectExchangeRequest) throws ApiException {
        ApiResponse<PostConnectExchange200Response> localVarResp = postConnectExchangeWithHttpInfo(postConnectExchangeRequest);
        return localVarResp.getData();
    }

    /**
     * Exchange authorization code for API credentials
     * Exchange a short-lived authorization code (obtained from the /connect flow) for the user&#39;s publishable key, secret key, and webhook secret. A webhook will be created using the provided endpoints.
     * @param postConnectExchangeRequest  (required)
     * @return ApiResponse&lt;PostConnectExchange200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PostConnectExchange200Response> postConnectExchangeWithHttpInfo(@javax.annotation.Nonnull PostConnectExchangeRequest postConnectExchangeRequest) throws ApiException {
        okhttp3.Call localVarCall = postConnectExchangeValidateBeforeCall(postConnectExchangeRequest, null);
        Type localVarReturnType = new TypeToken<PostConnectExchange200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Exchange authorization code for API credentials (asynchronously)
     * Exchange a short-lived authorization code (obtained from the /connect flow) for the user&#39;s publishable key, secret key, and webhook secret. A webhook will be created using the provided endpoints.
     * @param postConnectExchangeRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postConnectExchangeAsync(@javax.annotation.Nonnull PostConnectExchangeRequest postConnectExchangeRequest, final ApiCallback<PostConnectExchange200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = postConnectExchangeValidateBeforeCall(postConnectExchangeRequest, _callback);
        Type localVarReturnType = new TypeToken<PostConnectExchange200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
