/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiCallback;
import com.moosyl.ApiClient;
import com.moosyl.ApiException;
import com.moosyl.ApiResponse;
import com.moosyl.Configuration;
import com.moosyl.Pair;
import com.moosyl.ProgressRequestBody;
import com.moosyl.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.moosyl.model.GetProductsPageParameter;
import com.moosyl.model.InvoiceList;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InvoicesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InvoicesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InvoicesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getInvoices
     * @param id  (optional)
     * @param externalUserId  (optional)
     * @param subscriptionId  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInvoicesCall(@javax.annotation.Nullable String id, @javax.annotation.Nullable String externalUserId, @javax.annotation.Nullable String subscriptionId, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/invoices/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (id != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("id", id));
        }

        if (externalUserId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("externalUserId", externalUserId));
        }

        if (subscriptionId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("subscriptionId", subscriptionId));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getInvoicesValidateBeforeCall(@javax.annotation.Nullable String id, @javax.annotation.Nullable String externalUserId, @javax.annotation.Nullable String subscriptionId, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback _callback) throws ApiException {
        return getInvoicesCall(id, externalUserId, subscriptionId, page, limit, _callback);

    }

    /**
     * List invoices or filter by id/external user
     * 
     * @param id  (optional)
     * @param externalUserId  (optional)
     * @param subscriptionId  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @return InvoiceList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public InvoiceList getInvoices(@javax.annotation.Nullable String id, @javax.annotation.Nullable String externalUserId, @javax.annotation.Nullable String subscriptionId, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit) throws ApiException {
        ApiResponse<InvoiceList> localVarResp = getInvoicesWithHttpInfo(id, externalUserId, subscriptionId, page, limit);
        return localVarResp.getData();
    }

    /**
     * List invoices or filter by id/external user
     * 
     * @param id  (optional)
     * @param externalUserId  (optional)
     * @param subscriptionId  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @return ApiResponse&lt;InvoiceList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InvoiceList> getInvoicesWithHttpInfo(@javax.annotation.Nullable String id, @javax.annotation.Nullable String externalUserId, @javax.annotation.Nullable String subscriptionId, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit) throws ApiException {
        okhttp3.Call localVarCall = getInvoicesValidateBeforeCall(id, externalUserId, subscriptionId, page, limit, null);
        Type localVarReturnType = new TypeToken<InvoiceList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List invoices or filter by id/external user (asynchronously)
     * 
     * @param id  (optional)
     * @param externalUserId  (optional)
     * @param subscriptionId  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getInvoicesAsync(@javax.annotation.Nullable String id, @javax.annotation.Nullable String externalUserId, @javax.annotation.Nullable String subscriptionId, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback<InvoiceList> _callback) throws ApiException {

        okhttp3.Call localVarCall = getInvoicesValidateBeforeCall(id, externalUserId, subscriptionId, page, limit, _callback);
        Type localVarReturnType = new TypeToken<InvoiceList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
