/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiCallback;
import com.moosyl.ApiClient;
import com.moosyl.ApiException;
import com.moosyl.ApiResponse;
import com.moosyl.Configuration;
import com.moosyl.Pair;
import com.moosyl.ProgressRequestBody;
import com.moosyl.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.moosyl.model.GetProductsPageParameter;
import com.moosyl.model.ProductCreate;
import com.moosyl.model.ProductGet;
import com.moosyl.model.ProductGetWithPrices;
import com.moosyl.model.ProductList;
import com.moosyl.model.ProductUpdate;
import com.moosyl.model.Success;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ProductsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProductsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getProducts
     * @param id  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsCall(@javax.annotation.Nullable String id, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (id != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("id", id));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getProductsValidateBeforeCall(@javax.annotation.Nullable String id, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback _callback) throws ApiException {
        return getProductsCall(id, page, limit, _callback);

    }

    /**
     * List products or filter by id
     * 
     * @param id  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @return ProductList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ProductList getProducts(@javax.annotation.Nullable String id, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit) throws ApiException {
        ApiResponse<ProductList> localVarResp = getProductsWithHttpInfo(id, page, limit);
        return localVarResp.getData();
    }

    /**
     * List products or filter by id
     * 
     * @param id  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @return ApiResponse&lt;ProductList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductList> getProductsWithHttpInfo(@javax.annotation.Nullable String id, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit) throws ApiException {
        okhttp3.Call localVarCall = getProductsValidateBeforeCall(id, page, limit, null);
        Type localVarReturnType = new TypeToken<ProductList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List products or filter by id (asynchronously)
     * 
     * @param id  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsAsync(@javax.annotation.Nullable String id, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback<ProductList> _callback) throws ApiException {

        okhttp3.Call localVarCall = getProductsValidateBeforeCall(id, page, limit, _callback);
        Type localVarReturnType = new TypeToken<ProductList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getProductsById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getProductsByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getProductsById(Async)");
        }

        return getProductsByIdCall(id, _callback);

    }

    /**
     * Get product with prices
     * 
     * @param id  (required)
     * @return ProductGetWithPrices
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ProductGetWithPrices getProductsById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<ProductGetWithPrices> localVarResp = getProductsByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get product with prices
     * 
     * @param id  (required)
     * @return ApiResponse&lt;ProductGetWithPrices&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductGetWithPrices> getProductsByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getProductsByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ProductGetWithPrices>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get product with prices (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getProductsByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<ProductGetWithPrices> _callback) throws ApiException {

        okhttp3.Call localVarCall = getProductsByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ProductGetWithPrices>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for patchProductsById
     * @param id  (required)
     * @param productUpdate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchProductsByIdCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ProductUpdate productUpdate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = productUpdate;

        // create path and map variables
        String localVarPath = "/products/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call patchProductsByIdValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ProductUpdate productUpdate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling patchProductsById(Async)");
        }

        // verify the required parameter 'productUpdate' is set
        if (productUpdate == null) {
            throw new ApiException("Missing the required parameter 'productUpdate' when calling patchProductsById(Async)");
        }

        return patchProductsByIdCall(id, productUpdate, _callback);

    }

    /**
     * Update product
     * 
     * @param id  (required)
     * @param productUpdate  (required)
     * @return ProductGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ProductGet patchProductsById(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ProductUpdate productUpdate) throws ApiException {
        ApiResponse<ProductGet> localVarResp = patchProductsByIdWithHttpInfo(id, productUpdate);
        return localVarResp.getData();
    }

    /**
     * Update product
     * 
     * @param id  (required)
     * @param productUpdate  (required)
     * @return ApiResponse&lt;ProductGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductGet> patchProductsByIdWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ProductUpdate productUpdate) throws ApiException {
        okhttp3.Call localVarCall = patchProductsByIdValidateBeforeCall(id, productUpdate, null);
        Type localVarReturnType = new TypeToken<ProductGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update product (asynchronously)
     * 
     * @param id  (required)
     * @param productUpdate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchProductsByIdAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull ProductUpdate productUpdate, final ApiCallback<ProductGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = patchProductsByIdValidateBeforeCall(id, productUpdate, _callback);
        Type localVarReturnType = new TypeToken<ProductGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for patchProductsByIdArchive
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchProductsByIdArchiveCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/products/{id}/archive"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call patchProductsByIdArchiveValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling patchProductsByIdArchive(Async)");
        }

        return patchProductsByIdArchiveCall(id, _callback);

    }

    /**
     * Archive product
     * 
     * @param id  (required)
     * @return Success
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public Success patchProductsByIdArchive(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<Success> localVarResp = patchProductsByIdArchiveWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Archive product
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Success&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Success> patchProductsByIdArchiveWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = patchProductsByIdArchiveValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Success>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Archive product (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call patchProductsByIdArchiveAsync(@javax.annotation.Nonnull String id, final ApiCallback<Success> _callback) throws ApiException {

        okhttp3.Call localVarCall = patchProductsByIdArchiveValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Success>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postProducts
     * @param productCreate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postProductsCall(@javax.annotation.Nonnull ProductCreate productCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = productCreate;

        // create path and map variables
        String localVarPath = "/products/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postProductsValidateBeforeCall(@javax.annotation.Nonnull ProductCreate productCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'productCreate' is set
        if (productCreate == null) {
            throw new ApiException("Missing the required parameter 'productCreate' when calling postProducts(Async)");
        }

        return postProductsCall(productCreate, _callback);

    }

    /**
     * Create product
     * 
     * @param productCreate  (required)
     * @return ProductGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ProductGet postProducts(@javax.annotation.Nonnull ProductCreate productCreate) throws ApiException {
        ApiResponse<ProductGet> localVarResp = postProductsWithHttpInfo(productCreate);
        return localVarResp.getData();
    }

    /**
     * Create product
     * 
     * @param productCreate  (required)
     * @return ApiResponse&lt;ProductGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ProductGet> postProductsWithHttpInfo(@javax.annotation.Nonnull ProductCreate productCreate) throws ApiException {
        okhttp3.Call localVarCall = postProductsValidateBeforeCall(productCreate, null);
        Type localVarReturnType = new TypeToken<ProductGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create product (asynchronously)
     * 
     * @param productCreate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postProductsAsync(@javax.annotation.Nonnull ProductCreate productCreate, final ApiCallback<ProductGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = postProductsValidateBeforeCall(productCreate, _callback);
        Type localVarReturnType = new TypeToken<ProductGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
