/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiCallback;
import com.moosyl.ApiClient;
import com.moosyl.ApiException;
import com.moosyl.ApiResponse;
import com.moosyl.Configuration;
import com.moosyl.Pair;
import com.moosyl.ProgressRequestBody;
import com.moosyl.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.moosyl.model.GetProductsPageParameter;
import com.moosyl.model.SubscriptionCreate;
import com.moosyl.model.SubscriptionCreateByExternalUser;
import com.moosyl.model.SubscriptionGet;
import com.moosyl.model.SubscriptionList;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SubscriptionsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SubscriptionsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SubscriptionsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getSubscriptions
     * @param status  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionsCall(@javax.annotation.Nullable String status, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/subscriptions/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (status != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("status", status));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSubscriptionsValidateBeforeCall(@javax.annotation.Nullable String status, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback _callback) throws ApiException {
        return getSubscriptionsCall(status, page, limit, _callback);

    }

    /**
     * List subscriptions
     * 
     * @param status  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @return SubscriptionList
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionList getSubscriptions(@javax.annotation.Nullable String status, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit) throws ApiException {
        ApiResponse<SubscriptionList> localVarResp = getSubscriptionsWithHttpInfo(status, page, limit);
        return localVarResp.getData();
    }

    /**
     * List subscriptions
     * 
     * @param status  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @return ApiResponse&lt;SubscriptionList&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionList> getSubscriptionsWithHttpInfo(@javax.annotation.Nullable String status, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit) throws ApiException {
        okhttp3.Call localVarCall = getSubscriptionsValidateBeforeCall(status, page, limit, null);
        Type localVarReturnType = new TypeToken<SubscriptionList>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List subscriptions (asynchronously)
     * 
     * @param status  (optional)
     * @param page  (optional)
     * @param limit  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionsAsync(@javax.annotation.Nullable String status, @javax.annotation.Nullable GetProductsPageParameter page, @javax.annotation.Nullable GetProductsPageParameter limit, final ApiCallback<SubscriptionList> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSubscriptionsValidateBeforeCall(status, page, limit, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionList>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getSubscriptionsByExternalUserByExternalUserId
     * @param externalUserId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionsByExternalUserByExternalUserIdCall(@javax.annotation.Nonnull String externalUserId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/subscriptions/by-external-user/{externalUserId}"
            .replace("{" + "externalUserId" + "}", localVarApiClient.escapeString(externalUserId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSubscriptionsByExternalUserByExternalUserIdValidateBeforeCall(@javax.annotation.Nonnull String externalUserId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'externalUserId' is set
        if (externalUserId == null) {
            throw new ApiException("Missing the required parameter 'externalUserId' when calling getSubscriptionsByExternalUserByExternalUserId(Async)");
        }

        return getSubscriptionsByExternalUserByExternalUserIdCall(externalUserId, _callback);

    }

    /**
     * Get subscription by external user
     * 
     * @param externalUserId  (required)
     * @return SubscriptionGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionGet getSubscriptionsByExternalUserByExternalUserId(@javax.annotation.Nonnull String externalUserId) throws ApiException {
        ApiResponse<SubscriptionGet> localVarResp = getSubscriptionsByExternalUserByExternalUserIdWithHttpInfo(externalUserId);
        return localVarResp.getData();
    }

    /**
     * Get subscription by external user
     * 
     * @param externalUserId  (required)
     * @return ApiResponse&lt;SubscriptionGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionGet> getSubscriptionsByExternalUserByExternalUserIdWithHttpInfo(@javax.annotation.Nonnull String externalUserId) throws ApiException {
        okhttp3.Call localVarCall = getSubscriptionsByExternalUserByExternalUserIdValidateBeforeCall(externalUserId, null);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get subscription by external user (asynchronously)
     * 
     * @param externalUserId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionsByExternalUserByExternalUserIdAsync(@javax.annotation.Nonnull String externalUserId, final ApiCallback<SubscriptionGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSubscriptionsByExternalUserByExternalUserIdValidateBeforeCall(externalUserId, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getSubscriptionsById
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionsByIdCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/subscriptions/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getSubscriptionsByIdValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getSubscriptionsById(Async)");
        }

        return getSubscriptionsByIdCall(id, _callback);

    }

    /**
     * Get subscription
     * 
     * @param id  (required)
     * @return SubscriptionGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionGet getSubscriptionsById(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<SubscriptionGet> localVarResp = getSubscriptionsByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get subscription
     * 
     * @param id  (required)
     * @return ApiResponse&lt;SubscriptionGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionGet> getSubscriptionsByIdWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = getSubscriptionsByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get subscription (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getSubscriptionsByIdAsync(@javax.annotation.Nonnull String id, final ApiCallback<SubscriptionGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = getSubscriptionsByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postSubscriptions
     * @param subscriptionCreate  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubscriptionsCall(@javax.annotation.Nonnull SubscriptionCreate subscriptionCreate, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = subscriptionCreate;

        // create path and map variables
        String localVarPath = "/subscriptions/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postSubscriptionsValidateBeforeCall(@javax.annotation.Nonnull SubscriptionCreate subscriptionCreate, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'subscriptionCreate' is set
        if (subscriptionCreate == null) {
            throw new ApiException("Missing the required parameter 'subscriptionCreate' when calling postSubscriptions(Async)");
        }

        return postSubscriptionsCall(subscriptionCreate, _callback);

    }

    /**
     * Create subscription
     * 
     * @param subscriptionCreate  (required)
     * @return SubscriptionGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionGet postSubscriptions(@javax.annotation.Nonnull SubscriptionCreate subscriptionCreate) throws ApiException {
        ApiResponse<SubscriptionGet> localVarResp = postSubscriptionsWithHttpInfo(subscriptionCreate);
        return localVarResp.getData();
    }

    /**
     * Create subscription
     * 
     * @param subscriptionCreate  (required)
     * @return ApiResponse&lt;SubscriptionGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionGet> postSubscriptionsWithHttpInfo(@javax.annotation.Nonnull SubscriptionCreate subscriptionCreate) throws ApiException {
        okhttp3.Call localVarCall = postSubscriptionsValidateBeforeCall(subscriptionCreate, null);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create subscription (asynchronously)
     * 
     * @param subscriptionCreate  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubscriptionsAsync(@javax.annotation.Nonnull SubscriptionCreate subscriptionCreate, final ApiCallback<SubscriptionGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = postSubscriptionsValidateBeforeCall(subscriptionCreate, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postSubscriptionsByExternalUser
     * @param subscriptionCreateByExternalUser  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubscriptionsByExternalUserCall(@javax.annotation.Nonnull SubscriptionCreateByExternalUser subscriptionCreateByExternalUser, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = subscriptionCreateByExternalUser;

        // create path and map variables
        String localVarPath = "/subscriptions/by-external-user";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postSubscriptionsByExternalUserValidateBeforeCall(@javax.annotation.Nonnull SubscriptionCreateByExternalUser subscriptionCreateByExternalUser, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'subscriptionCreateByExternalUser' is set
        if (subscriptionCreateByExternalUser == null) {
            throw new ApiException("Missing the required parameter 'subscriptionCreateByExternalUser' when calling postSubscriptionsByExternalUser(Async)");
        }

        return postSubscriptionsByExternalUserCall(subscriptionCreateByExternalUser, _callback);

    }

    /**
     * Create subscription by external user
     * 
     * @param subscriptionCreateByExternalUser  (required)
     * @return SubscriptionGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionGet postSubscriptionsByExternalUser(@javax.annotation.Nonnull SubscriptionCreateByExternalUser subscriptionCreateByExternalUser) throws ApiException {
        ApiResponse<SubscriptionGet> localVarResp = postSubscriptionsByExternalUserWithHttpInfo(subscriptionCreateByExternalUser);
        return localVarResp.getData();
    }

    /**
     * Create subscription by external user
     * 
     * @param subscriptionCreateByExternalUser  (required)
     * @return ApiResponse&lt;SubscriptionGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionGet> postSubscriptionsByExternalUserWithHttpInfo(@javax.annotation.Nonnull SubscriptionCreateByExternalUser subscriptionCreateByExternalUser) throws ApiException {
        okhttp3.Call localVarCall = postSubscriptionsByExternalUserValidateBeforeCall(subscriptionCreateByExternalUser, null);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create subscription by external user (asynchronously)
     * 
     * @param subscriptionCreateByExternalUser  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubscriptionsByExternalUserAsync(@javax.annotation.Nonnull SubscriptionCreateByExternalUser subscriptionCreateByExternalUser, final ApiCallback<SubscriptionGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = postSubscriptionsByExternalUserValidateBeforeCall(subscriptionCreateByExternalUser, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for postSubscriptionsByIdCancel
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubscriptionsByIdCancelCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/subscriptions/{id}/cancel"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postSubscriptionsByIdCancelValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling postSubscriptionsByIdCancel(Async)");
        }

        return postSubscriptionsByIdCancelCall(id, _callback);

    }

    /**
     * Cancel subscription
     * 
     * @param id  (required)
     * @return SubscriptionGet
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionGet postSubscriptionsByIdCancel(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<SubscriptionGet> localVarResp = postSubscriptionsByIdCancelWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Cancel subscription
     * 
     * @param id  (required)
     * @return ApiResponse&lt;SubscriptionGet&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionGet> postSubscriptionsByIdCancelWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = postSubscriptionsByIdCancelValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Cancel subscription (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Response for status 200 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postSubscriptionsByIdCancelAsync(@javax.annotation.Nonnull String id, final ApiCallback<SubscriptionGet> _callback) throws ApiException {

        okhttp3.Call localVarCall = postSubscriptionsByIdCancelValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionGet>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
