/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.moosyl.model.CheckoutSessionCreateData;
import com.moosyl.model.CheckoutSessionGetLatestPayment;
import com.moosyl.model.ConfigurationListDataInner;
import com.moosyl.model.GetOrganizationById200ResponseData;
import com.moosyl.model.PaymentRequestGetData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CheckoutSessionSwitchMethod
 */
public class CheckoutSessionSwitchMethodTest {
    private final CheckoutSessionSwitchMethod model = new CheckoutSessionSwitchMethod();

    /**
     * Model tests for CheckoutSessionSwitchMethod
     */
    @Test
    public void testCheckoutSessionSwitchMethod() {
        // TODO: test CheckoutSessionSwitchMethod
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'paymentRequest'
     */
    @Test
    public void paymentRequestTest() {
        // TODO: test paymentRequest
    }

    /**
     * Test the property 'configurations'
     */
    @Test
    public void configurationsTest() {
        // TODO: test configurations
    }

    /**
     * Test the property 'latestPayment'
     */
    @Test
    public void latestPaymentTest() {
        // TODO: test latestPayment
    }

}
