/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostConnectExchange200ResponseData
 */
public class PostConnectExchange200ResponseDataTest {
    private final PostConnectExchange200ResponseData model = new PostConnectExchange200ResponseData();

    /**
     * Model tests for PostConnectExchange200ResponseData
     */
    @Test
    public void testPostConnectExchange200ResponseData() {
        // TODO: test PostConnectExchange200ResponseData
    }

    /**
     * Test the property 'publishableKey'
     */
    @Test
    public void publishableKeyTest() {
        // TODO: test publishableKey
    }

    /**
     * Test the property 'secretKey'
     */
    @Test
    public void secretKeyTest() {
        // TODO: test secretKey
    }

    /**
     * Test the property 'webhookSecret'
     */
    @Test
    public void webhookSecretTest() {
        // TODO: test webhookSecret
    }

}
