/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.moosyl.model.SubscriptionCreateTrial;
import com.moosyl.model.SubscriptionCreateTrialEnd;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscriptionCreateByExternalUser
 */
public class SubscriptionCreateByExternalUserTest {
    private final SubscriptionCreateByExternalUser model = new SubscriptionCreateByExternalUser();

    /**
     * Model tests for SubscriptionCreateByExternalUser
     */
    @Test
    public void testSubscriptionCreateByExternalUser() {
        // TODO: test SubscriptionCreateByExternalUser
    }

    /**
     * Test the property 'externalUserId'
     */
    @Test
    public void externalUserIdTest() {
        // TODO: test externalUserId
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'priceId'
     */
    @Test
    public void priceIdTest() {
        // TODO: test priceId
    }

    /**
     * Test the property 'trial'
     */
    @Test
    public void trialTest() {
        // TODO: test trial
    }

    /**
     * Test the property 'trialPeriod'
     */
    @Test
    public void trialPeriodTest() {
        // TODO: test trialPeriod
    }

    /**
     * Test the property 'trialEnd'
     */
    @Test
    public void trialEndTest() {
        // TODO: test trialEnd
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

}
