/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubscriptionCreateTrial
 */
public class SubscriptionCreateTrialTest {
    private final SubscriptionCreateTrial model = new SubscriptionCreateTrial();

    /**
     * Model tests for SubscriptionCreateTrial
     */
    @Test
    public void testSubscriptionCreateTrial() {
        // TODO: test SubscriptionCreateTrial
    }

}
