/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.moosyl.model.CheckoutSessionCreateData;
import com.moosyl.model.CheckoutSessionGetLatestPayment;
import com.moosyl.model.ConfigurationListDataInner;
import com.moosyl.model.GetOrganizationById200ResponseData;
import com.moosyl.model.PaymentRequestGetData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.moosyl.JSON;

/**
 * CheckoutSessionSwitchMethod
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class CheckoutSessionSwitchMethod {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nonnull
  private CheckoutSessionCreateData data;

  public static final String SERIALIZED_NAME_ORGANIZATION = "organization";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION)
  @javax.annotation.Nonnull
  private GetOrganizationById200ResponseData organization;

  public static final String SERIALIZED_NAME_PAYMENT_REQUEST = "paymentRequest";
  @SerializedName(SERIALIZED_NAME_PAYMENT_REQUEST)
  @javax.annotation.Nonnull
  private PaymentRequestGetData paymentRequest;

  public static final String SERIALIZED_NAME_CONFIGURATIONS = "configurations";
  @SerializedName(SERIALIZED_NAME_CONFIGURATIONS)
  @javax.annotation.Nonnull
  private List<ConfigurationListDataInner> configurations = new ArrayList<>();

  public static final String SERIALIZED_NAME_LATEST_PAYMENT = "latestPayment";
  @SerializedName(SERIALIZED_NAME_LATEST_PAYMENT)
  @javax.annotation.Nullable
  private CheckoutSessionGetLatestPayment latestPayment;

  public CheckoutSessionSwitchMethod() {
  }

  public CheckoutSessionSwitchMethod data(@javax.annotation.Nonnull CheckoutSessionCreateData data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nonnull
  public CheckoutSessionCreateData getData() {
    return data;
  }

  public void setData(@javax.annotation.Nonnull CheckoutSessionCreateData data) {
    this.data = data;
  }


  public CheckoutSessionSwitchMethod organization(@javax.annotation.Nonnull GetOrganizationById200ResponseData organization) {
    this.organization = organization;
    return this;
  }

  /**
   * Get organization
   * @return organization
   */
  @javax.annotation.Nonnull
  public GetOrganizationById200ResponseData getOrganization() {
    return organization;
  }

  public void setOrganization(@javax.annotation.Nonnull GetOrganizationById200ResponseData organization) {
    this.organization = organization;
  }


  public CheckoutSessionSwitchMethod paymentRequest(@javax.annotation.Nonnull PaymentRequestGetData paymentRequest) {
    this.paymentRequest = paymentRequest;
    return this;
  }

  /**
   * Get paymentRequest
   * @return paymentRequest
   */
  @javax.annotation.Nonnull
  public PaymentRequestGetData getPaymentRequest() {
    return paymentRequest;
  }

  public void setPaymentRequest(@javax.annotation.Nonnull PaymentRequestGetData paymentRequest) {
    this.paymentRequest = paymentRequest;
  }


  public CheckoutSessionSwitchMethod configurations(@javax.annotation.Nonnull List<ConfigurationListDataInner> configurations) {
    this.configurations = configurations;
    return this;
  }

  public CheckoutSessionSwitchMethod addConfigurationsItem(ConfigurationListDataInner configurationsItem) {
    if (this.configurations == null) {
      this.configurations = new ArrayList<>();
    }
    this.configurations.add(configurationsItem);
    return this;
  }

  /**
   * Get configurations
   * @return configurations
   */
  @javax.annotation.Nonnull
  public List<ConfigurationListDataInner> getConfigurations() {
    return configurations;
  }

  public void setConfigurations(@javax.annotation.Nonnull List<ConfigurationListDataInner> configurations) {
    this.configurations = configurations;
  }


  public CheckoutSessionSwitchMethod latestPayment(@javax.annotation.Nullable CheckoutSessionGetLatestPayment latestPayment) {
    this.latestPayment = latestPayment;
    return this;
  }

  /**
   * Get latestPayment
   * @return latestPayment
   */
  @javax.annotation.Nullable
  public CheckoutSessionGetLatestPayment getLatestPayment() {
    return latestPayment;
  }

  public void setLatestPayment(@javax.annotation.Nullable CheckoutSessionGetLatestPayment latestPayment) {
    this.latestPayment = latestPayment;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutSessionSwitchMethod checkoutSessionSwitchMethod = (CheckoutSessionSwitchMethod) o;
    return Objects.equals(this.data, checkoutSessionSwitchMethod.data) &&
        Objects.equals(this.organization, checkoutSessionSwitchMethod.organization) &&
        Objects.equals(this.paymentRequest, checkoutSessionSwitchMethod.paymentRequest) &&
        Objects.equals(this.configurations, checkoutSessionSwitchMethod.configurations) &&
        Objects.equals(this.latestPayment, checkoutSessionSwitchMethod.latestPayment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, organization, paymentRequest, configurations, latestPayment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutSessionSwitchMethod {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    paymentRequest: ").append(toIndentedString(paymentRequest)).append("\n");
    sb.append("    configurations: ").append(toIndentedString(configurations)).append("\n");
    sb.append("    latestPayment: ").append(toIndentedString(latestPayment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("data", "organization", "paymentRequest", "configurations", "latestPayment"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("data", "organization", "paymentRequest", "configurations"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CheckoutSessionSwitchMethod
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CheckoutSessionSwitchMethod.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CheckoutSessionSwitchMethod is not found in the empty JSON string", CheckoutSessionSwitchMethod.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CheckoutSessionSwitchMethod.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CheckoutSessionSwitchMethod` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CheckoutSessionSwitchMethod.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `data`
      CheckoutSessionCreateData.validateJsonElement(jsonObj.get("data"));
      // validate the required field `organization`
      GetOrganizationById200ResponseData.validateJsonElement(jsonObj.get("organization"));
      // validate the required field `paymentRequest`
      PaymentRequestGetData.validateJsonElement(jsonObj.get("paymentRequest"));
      if (jsonObj.get("configurations") != null) {
        if (!jsonObj.get("configurations").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `configurations` to be an array in the JSON string but got `%s`", jsonObj.get("configurations").toString()));
        }
        JsonArray jsonArrayconfigurations = jsonObj.getAsJsonArray("configurations");
        // validate the required field `configurations` (array)
        for (int i = 0; i < jsonArrayconfigurations.size(); i++) {
          ConfigurationListDataInner.validateJsonElement(jsonArrayconfigurations.get(i));
        }
      }
      // validate the optional field `latestPayment`
      if (jsonObj.get("latestPayment") != null && !jsonObj.get("latestPayment").isJsonNull()) {
        CheckoutSessionGetLatestPayment.validateJsonElement(jsonObj.get("latestPayment"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CheckoutSessionSwitchMethod.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CheckoutSessionSwitchMethod' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CheckoutSessionSwitchMethod> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CheckoutSessionSwitchMethod.class));

       return (TypeAdapter<T>) new TypeAdapter<CheckoutSessionSwitchMethod>() {
           @Override
           public void write(JsonWriter out, CheckoutSessionSwitchMethod value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CheckoutSessionSwitchMethod read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CheckoutSessionSwitchMethod given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CheckoutSessionSwitchMethod
   * @throws IOException if the JSON string is invalid with respect to CheckoutSessionSwitchMethod
   */
  public static CheckoutSessionSwitchMethod fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CheckoutSessionSwitchMethod.class);
  }

  /**
   * Convert an instance of CheckoutSessionSwitchMethod to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

