/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.moosyl.JSON;

/**
 * DeleteConnectRevokeRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class DeleteConnectRevokeRequest {
  public static final String SERIALIZED_NAME_PLATFORM_ID = "platform_id";
  @SerializedName(SERIALIZED_NAME_PLATFORM_ID)
  @javax.annotation.Nonnull
  private String platformId;

  public static final String SERIALIZED_NAME_PLATFORM_SECRET = "platform_secret";
  @SerializedName(SERIALIZED_NAME_PLATFORM_SECRET)
  @javax.annotation.Nonnull
  private String platformSecret;

  public static final String SERIALIZED_NAME_CONNECTION_ID = "connection_id";
  @SerializedName(SERIALIZED_NAME_CONNECTION_ID)
  @javax.annotation.Nonnull
  private String connectionId;

  public DeleteConnectRevokeRequest() {
  }

  public DeleteConnectRevokeRequest platformId(@javax.annotation.Nonnull String platformId) {
    this.platformId = platformId;
    return this;
  }

  /**
   * Get platformId
   * @return platformId
   */
  @javax.annotation.Nonnull
  public String getPlatformId() {
    return platformId;
  }

  public void setPlatformId(@javax.annotation.Nonnull String platformId) {
    this.platformId = platformId;
  }


  public DeleteConnectRevokeRequest platformSecret(@javax.annotation.Nonnull String platformSecret) {
    this.platformSecret = platformSecret;
    return this;
  }

  /**
   * Get platformSecret
   * @return platformSecret
   */
  @javax.annotation.Nonnull
  public String getPlatformSecret() {
    return platformSecret;
  }

  public void setPlatformSecret(@javax.annotation.Nonnull String platformSecret) {
    this.platformSecret = platformSecret;
  }


  public DeleteConnectRevokeRequest connectionId(@javax.annotation.Nonnull String connectionId) {
    this.connectionId = connectionId;
    return this;
  }

  /**
   * Get connectionId
   * @return connectionId
   */
  @javax.annotation.Nonnull
  public String getConnectionId() {
    return connectionId;
  }

  public void setConnectionId(@javax.annotation.Nonnull String connectionId) {
    this.connectionId = connectionId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteConnectRevokeRequest deleteConnectRevokeRequest = (DeleteConnectRevokeRequest) o;
    return Objects.equals(this.platformId, deleteConnectRevokeRequest.platformId) &&
        Objects.equals(this.platformSecret, deleteConnectRevokeRequest.platformSecret) &&
        Objects.equals(this.connectionId, deleteConnectRevokeRequest.connectionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(platformId, platformSecret, connectionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteConnectRevokeRequest {\n");
    sb.append("    platformId: ").append(toIndentedString(platformId)).append("\n");
    sb.append("    platformSecret: ").append(toIndentedString(platformSecret)).append("\n");
    sb.append("    connectionId: ").append(toIndentedString(connectionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("platform_id", "platform_secret", "connection_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("platform_id", "platform_secret", "connection_id"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeleteConnectRevokeRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeleteConnectRevokeRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DeleteConnectRevokeRequest is not found in the empty JSON string", DeleteConnectRevokeRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeleteConnectRevokeRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DeleteConnectRevokeRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeleteConnectRevokeRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("platform_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `platform_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform_id").toString()));
      }
      if (!jsonObj.get("platform_secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `platform_secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("platform_secret").toString()));
      }
      if (!jsonObj.get("connection_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `connection_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connection_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeleteConnectRevokeRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeleteConnectRevokeRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeleteConnectRevokeRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeleteConnectRevokeRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeleteConnectRevokeRequest>() {
           @Override
           public void write(JsonWriter out, DeleteConnectRevokeRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeleteConnectRevokeRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeleteConnectRevokeRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeleteConnectRevokeRequest
   * @throws IOException if the JSON string is invalid with respect to DeleteConnectRevokeRequest
   */
  public static DeleteConnectRevokeRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeleteConnectRevokeRequest.class);
  }

  /**
   * Convert an instance of DeleteConnectRevokeRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

