/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.moosyl.JSON;

/**
 * PaymentRequestRefreshStatusBankingApiResponsesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class PaymentRequestRefreshStatusBankingApiResponsesInner {
  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nonnull
  private String transactionId;

  public static final String SERIALIZED_NAME_CONFIGURATION_ID = "configurationId";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION_ID)
  @javax.annotation.Nonnull
  private String configurationId;

  public static final String SERIALIZED_NAME_CONFIGURATION_TYPE = "configurationType";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION_TYPE)
  @javax.annotation.Nonnull
  private String configurationType;

  public static final String SERIALIZED_NAME_OUTCOME = "outcome";
  @SerializedName(SERIALIZED_NAME_OUTCOME)
  @javax.annotation.Nonnull
  private String outcome;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  @javax.annotation.Nonnull
  private String body;

  public PaymentRequestRefreshStatusBankingApiResponsesInner() {
  }

  public PaymentRequestRefreshStatusBankingApiResponsesInner transactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
  }


  public PaymentRequestRefreshStatusBankingApiResponsesInner configurationId(@javax.annotation.Nonnull String configurationId) {
    this.configurationId = configurationId;
    return this;
  }

  /**
   * Get configurationId
   * @return configurationId
   */
  @javax.annotation.Nonnull
  public String getConfigurationId() {
    return configurationId;
  }

  public void setConfigurationId(@javax.annotation.Nonnull String configurationId) {
    this.configurationId = configurationId;
  }


  public PaymentRequestRefreshStatusBankingApiResponsesInner configurationType(@javax.annotation.Nonnull String configurationType) {
    this.configurationType = configurationType;
    return this;
  }

  /**
   * Get configurationType
   * @return configurationType
   */
  @javax.annotation.Nonnull
  public String getConfigurationType() {
    return configurationType;
  }

  public void setConfigurationType(@javax.annotation.Nonnull String configurationType) {
    this.configurationType = configurationType;
  }


  public PaymentRequestRefreshStatusBankingApiResponsesInner outcome(@javax.annotation.Nonnull String outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * Get outcome
   * @return outcome
   */
  @javax.annotation.Nonnull
  public String getOutcome() {
    return outcome;
  }

  public void setOutcome(@javax.annotation.Nonnull String outcome) {
    this.outcome = outcome;
  }


  public PaymentRequestRefreshStatusBankingApiResponsesInner body(@javax.annotation.Nonnull String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @javax.annotation.Nonnull
  public String getBody() {
    return body;
  }

  public void setBody(@javax.annotation.Nonnull String body) {
    this.body = body;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequestRefreshStatusBankingApiResponsesInner paymentRequestRefreshStatusBankingApiResponsesInner = (PaymentRequestRefreshStatusBankingApiResponsesInner) o;
    return Objects.equals(this.transactionId, paymentRequestRefreshStatusBankingApiResponsesInner.transactionId) &&
        Objects.equals(this.configurationId, paymentRequestRefreshStatusBankingApiResponsesInner.configurationId) &&
        Objects.equals(this.configurationType, paymentRequestRefreshStatusBankingApiResponsesInner.configurationType) &&
        Objects.equals(this.outcome, paymentRequestRefreshStatusBankingApiResponsesInner.outcome) &&
        Objects.equals(this.body, paymentRequestRefreshStatusBankingApiResponsesInner.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, configurationId, configurationType, outcome, body);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequestRefreshStatusBankingApiResponsesInner {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    configurationId: ").append(toIndentedString(configurationId)).append("\n");
    sb.append("    configurationType: ").append(toIndentedString(configurationType)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("transactionId", "configurationId", "configurationType", "outcome", "body"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("transactionId", "configurationId", "configurationType", "outcome", "body"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PaymentRequestRefreshStatusBankingApiResponsesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentRequestRefreshStatusBankingApiResponsesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PaymentRequestRefreshStatusBankingApiResponsesInner is not found in the empty JSON string", PaymentRequestRefreshStatusBankingApiResponsesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PaymentRequestRefreshStatusBankingApiResponsesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PaymentRequestRefreshStatusBankingApiResponsesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PaymentRequestRefreshStatusBankingApiResponsesInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("transactionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transactionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionId").toString()));
      }
      if (!jsonObj.get("configurationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `configurationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("configurationId").toString()));
      }
      if (!jsonObj.get("configurationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `configurationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("configurationType").toString()));
      }
      if (!jsonObj.get("outcome").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `outcome` to be a primitive type in the JSON string but got `%s`", jsonObj.get("outcome").toString()));
      }
      if (!jsonObj.get("body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("body").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentRequestRefreshStatusBankingApiResponsesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentRequestRefreshStatusBankingApiResponsesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentRequestRefreshStatusBankingApiResponsesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentRequestRefreshStatusBankingApiResponsesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentRequestRefreshStatusBankingApiResponsesInner>() {
           @Override
           public void write(JsonWriter out, PaymentRequestRefreshStatusBankingApiResponsesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentRequestRefreshStatusBankingApiResponsesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PaymentRequestRefreshStatusBankingApiResponsesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentRequestRefreshStatusBankingApiResponsesInner
   * @throws IOException if the JSON string is invalid with respect to PaymentRequestRefreshStatusBankingApiResponsesInner
   */
  public static PaymentRequestRefreshStatusBankingApiResponsesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentRequestRefreshStatusBankingApiResponsesInner.class);
  }

  /**
   * Convert an instance of PaymentRequestRefreshStatusBankingApiResponsesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

