/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.moosyl.JSON;

/**
 * PostMasriviInitiateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class PostMasriviInitiateRequest {
  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nonnull
  private String transactionId;

  public static final String SERIALIZED_NAME_CONFIGURATION_ID = "configurationId";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION_ID)
  @javax.annotation.Nonnull
  private String configurationId;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "phoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  @javax.annotation.Nullable
  private String phoneNumber;

  public static final String SERIALIZED_NAME_ACCEPT_URL = "acceptUrl";
  @SerializedName(SERIALIZED_NAME_ACCEPT_URL)
  @javax.annotation.Nullable
  private String acceptUrl;

  public static final String SERIALIZED_NAME_DECLINE_URL = "declineUrl";
  @SerializedName(SERIALIZED_NAME_DECLINE_URL)
  @javax.annotation.Nullable
  private String declineUrl;

  public static final String SERIALIZED_NAME_CANCEL_URL = "cancelUrl";
  @SerializedName(SERIALIZED_NAME_CANCEL_URL)
  @javax.annotation.Nullable
  private String cancelUrl;

  public PostMasriviInitiateRequest() {
  }

  public PostMasriviInitiateRequest transactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
  }


  public PostMasriviInitiateRequest configurationId(@javax.annotation.Nonnull String configurationId) {
    this.configurationId = configurationId;
    return this;
  }

  /**
   * Get configurationId
   * @return configurationId
   */
  @javax.annotation.Nonnull
  public String getConfigurationId() {
    return configurationId;
  }

  public void setConfigurationId(@javax.annotation.Nonnull String configurationId) {
    this.configurationId = configurationId;
  }


  public PostMasriviInitiateRequest phoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public PostMasriviInitiateRequest acceptUrl(@javax.annotation.Nullable String acceptUrl) {
    this.acceptUrl = acceptUrl;
    return this;
  }

  /**
   * Get acceptUrl
   * @return acceptUrl
   */
  @javax.annotation.Nullable
  public String getAcceptUrl() {
    return acceptUrl;
  }

  public void setAcceptUrl(@javax.annotation.Nullable String acceptUrl) {
    this.acceptUrl = acceptUrl;
  }


  public PostMasriviInitiateRequest declineUrl(@javax.annotation.Nullable String declineUrl) {
    this.declineUrl = declineUrl;
    return this;
  }

  /**
   * Get declineUrl
   * @return declineUrl
   */
  @javax.annotation.Nullable
  public String getDeclineUrl() {
    return declineUrl;
  }

  public void setDeclineUrl(@javax.annotation.Nullable String declineUrl) {
    this.declineUrl = declineUrl;
  }


  public PostMasriviInitiateRequest cancelUrl(@javax.annotation.Nullable String cancelUrl) {
    this.cancelUrl = cancelUrl;
    return this;
  }

  /**
   * Get cancelUrl
   * @return cancelUrl
   */
  @javax.annotation.Nullable
  public String getCancelUrl() {
    return cancelUrl;
  }

  public void setCancelUrl(@javax.annotation.Nullable String cancelUrl) {
    this.cancelUrl = cancelUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostMasriviInitiateRequest postMasriviInitiateRequest = (PostMasriviInitiateRequest) o;
    return Objects.equals(this.transactionId, postMasriviInitiateRequest.transactionId) &&
        Objects.equals(this.configurationId, postMasriviInitiateRequest.configurationId) &&
        Objects.equals(this.phoneNumber, postMasriviInitiateRequest.phoneNumber) &&
        Objects.equals(this.acceptUrl, postMasriviInitiateRequest.acceptUrl) &&
        Objects.equals(this.declineUrl, postMasriviInitiateRequest.declineUrl) &&
        Objects.equals(this.cancelUrl, postMasriviInitiateRequest.cancelUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, configurationId, phoneNumber, acceptUrl, declineUrl, cancelUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostMasriviInitiateRequest {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    configurationId: ").append(toIndentedString(configurationId)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    acceptUrl: ").append(toIndentedString(acceptUrl)).append("\n");
    sb.append("    declineUrl: ").append(toIndentedString(declineUrl)).append("\n");
    sb.append("    cancelUrl: ").append(toIndentedString(cancelUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("transactionId", "configurationId", "phoneNumber", "acceptUrl", "declineUrl", "cancelUrl"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("transactionId", "configurationId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostMasriviInitiateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostMasriviInitiateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PostMasriviInitiateRequest is not found in the empty JSON string", PostMasriviInitiateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostMasriviInitiateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PostMasriviInitiateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostMasriviInitiateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("transactionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transactionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionId").toString()));
      }
      if (!jsonObj.get("configurationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `configurationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("configurationId").toString()));
      }
      if ((jsonObj.get("phoneNumber") != null && !jsonObj.get("phoneNumber").isJsonNull()) && !jsonObj.get("phoneNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `phoneNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phoneNumber").toString()));
      }
      if ((jsonObj.get("acceptUrl") != null && !jsonObj.get("acceptUrl").isJsonNull()) && !jsonObj.get("acceptUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `acceptUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("acceptUrl").toString()));
      }
      if ((jsonObj.get("declineUrl") != null && !jsonObj.get("declineUrl").isJsonNull()) && !jsonObj.get("declineUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `declineUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("declineUrl").toString()));
      }
      if ((jsonObj.get("cancelUrl") != null && !jsonObj.get("cancelUrl").isJsonNull()) && !jsonObj.get("cancelUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cancelUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cancelUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostMasriviInitiateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostMasriviInitiateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostMasriviInitiateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostMasriviInitiateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostMasriviInitiateRequest>() {
           @Override
           public void write(JsonWriter out, PostMasriviInitiateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostMasriviInitiateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostMasriviInitiateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostMasriviInitiateRequest
   * @throws IOException if the JSON string is invalid with respect to PostMasriviInitiateRequest
   */
  public static PostMasriviInitiateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostMasriviInitiateRequest.class);
  }

  /**
   * Convert an instance of PostMasriviInitiateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

