/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.moosyl.model.SubscriptionCreateTrial;
import com.moosyl.model.SubscriptionCreateTrialEnd;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.moosyl.JSON;

/**
 * SubscriptionCreate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class SubscriptionCreate {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customerId";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  @javax.annotation.Nonnull
  private UUID customerId;

  public static final String SERIALIZED_NAME_PRICE_ID = "priceId";
  @SerializedName(SERIALIZED_NAME_PRICE_ID)
  @javax.annotation.Nonnull
  private UUID priceId;

  public static final String SERIALIZED_NAME_CANCELLED_AT = "cancelledAt";
  @SerializedName(SERIALIZED_NAME_CANCELLED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime cancelledAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_TRIAL = "trial";
  @SerializedName(SERIALIZED_NAME_TRIAL)
  @javax.annotation.Nullable
  private SubscriptionCreateTrial trial;

  /**
   * Gets or Sets trialPeriod
   */
  @JsonAdapter(TrialPeriodEnum.Adapter.class)
  public enum TrialPeriodEnum {
    _1_WEEK("1_week"),
    
    _1_MONTH("1_month"),
    
    _1_YEAR("1_year");

    private String value;

    TrialPeriodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TrialPeriodEnum fromValue(String value) {
      for (TrialPeriodEnum b : TrialPeriodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TrialPeriodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TrialPeriodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TrialPeriodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TrialPeriodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TrialPeriodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TRIAL_PERIOD = "trialPeriod";
  @SerializedName(SERIALIZED_NAME_TRIAL_PERIOD)
  @javax.annotation.Nullable
  private TrialPeriodEnum trialPeriod;

  public static final String SERIALIZED_NAME_TRIAL_END = "trialEnd";
  @SerializedName(SERIALIZED_NAME_TRIAL_END)
  @javax.annotation.Nullable
  private SubscriptionCreateTrialEnd trialEnd;

  public static final String SERIALIZED_NAME_STARTED_AT = "startedAt";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  @javax.annotation.Nullable
  private SubscriptionCreateTrialEnd startedAt;

  public SubscriptionCreate() {
  }

  public SubscriptionCreate id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public SubscriptionCreate customerId(@javax.annotation.Nonnull UUID customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Get customerId
   * @return customerId
   */
  @javax.annotation.Nonnull
  public UUID getCustomerId() {
    return customerId;
  }

  public void setCustomerId(@javax.annotation.Nonnull UUID customerId) {
    this.customerId = customerId;
  }


  public SubscriptionCreate priceId(@javax.annotation.Nonnull UUID priceId) {
    this.priceId = priceId;
    return this;
  }

  /**
   * Get priceId
   * @return priceId
   */
  @javax.annotation.Nonnull
  public UUID getPriceId() {
    return priceId;
  }

  public void setPriceId(@javax.annotation.Nonnull UUID priceId) {
    this.priceId = priceId;
  }


  public SubscriptionCreate cancelledAt(@javax.annotation.Nullable OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
    return this;
  }

  /**
   * Get cancelledAt
   * @return cancelledAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCancelledAt() {
    return cancelledAt;
  }

  public void setCancelledAt(@javax.annotation.Nullable OffsetDateTime cancelledAt) {
    this.cancelledAt = cancelledAt;
  }


  public SubscriptionCreate expiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public SubscriptionCreate trial(@javax.annotation.Nullable SubscriptionCreateTrial trial) {
    this.trial = trial;
    return this;
  }

  /**
   * Get trial
   * @return trial
   */
  @javax.annotation.Nullable
  public SubscriptionCreateTrial getTrial() {
    return trial;
  }

  public void setTrial(@javax.annotation.Nullable SubscriptionCreateTrial trial) {
    this.trial = trial;
  }


  public SubscriptionCreate trialPeriod(@javax.annotation.Nullable TrialPeriodEnum trialPeriod) {
    this.trialPeriod = trialPeriod;
    return this;
  }

  /**
   * Get trialPeriod
   * @return trialPeriod
   */
  @javax.annotation.Nullable
  public TrialPeriodEnum getTrialPeriod() {
    return trialPeriod;
  }

  public void setTrialPeriod(@javax.annotation.Nullable TrialPeriodEnum trialPeriod) {
    this.trialPeriod = trialPeriod;
  }


  public SubscriptionCreate trialEnd(@javax.annotation.Nullable SubscriptionCreateTrialEnd trialEnd) {
    this.trialEnd = trialEnd;
    return this;
  }

  /**
   * Get trialEnd
   * @return trialEnd
   */
  @javax.annotation.Nullable
  public SubscriptionCreateTrialEnd getTrialEnd() {
    return trialEnd;
  }

  public void setTrialEnd(@javax.annotation.Nullable SubscriptionCreateTrialEnd trialEnd) {
    this.trialEnd = trialEnd;
  }


  public SubscriptionCreate startedAt(@javax.annotation.Nullable SubscriptionCreateTrialEnd startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * Get startedAt
   * @return startedAt
   */
  @javax.annotation.Nullable
  public SubscriptionCreateTrialEnd getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(@javax.annotation.Nullable SubscriptionCreateTrialEnd startedAt) {
    this.startedAt = startedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionCreate subscriptionCreate = (SubscriptionCreate) o;
    return Objects.equals(this.id, subscriptionCreate.id) &&
        Objects.equals(this.customerId, subscriptionCreate.customerId) &&
        Objects.equals(this.priceId, subscriptionCreate.priceId) &&
        Objects.equals(this.cancelledAt, subscriptionCreate.cancelledAt) &&
        Objects.equals(this.expiresAt, subscriptionCreate.expiresAt) &&
        Objects.equals(this.trial, subscriptionCreate.trial) &&
        Objects.equals(this.trialPeriod, subscriptionCreate.trialPeriod) &&
        Objects.equals(this.trialEnd, subscriptionCreate.trialEnd) &&
        Objects.equals(this.startedAt, subscriptionCreate.startedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customerId, priceId, cancelledAt, expiresAt, trial, trialPeriod, trialEnd, startedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionCreate {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    priceId: ").append(toIndentedString(priceId)).append("\n");
    sb.append("    cancelledAt: ").append(toIndentedString(cancelledAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    trial: ").append(toIndentedString(trial)).append("\n");
    sb.append("    trialPeriod: ").append(toIndentedString(trialPeriod)).append("\n");
    sb.append("    trialEnd: ").append(toIndentedString(trialEnd)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "customerId", "priceId", "cancelledAt", "expiresAt", "trial", "trialPeriod", "trialEnd", "startedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("customerId", "priceId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubscriptionCreate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubscriptionCreate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SubscriptionCreate is not found in the empty JSON string", SubscriptionCreate.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubscriptionCreate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SubscriptionCreate` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubscriptionCreate.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("customerId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `customerId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerId").toString()));
      }
      if (!jsonObj.get("priceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `priceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("priceId").toString()));
      }
      // validate the optional field `trial`
      if (jsonObj.get("trial") != null && !jsonObj.get("trial").isJsonNull()) {
        SubscriptionCreateTrial.validateJsonElement(jsonObj.get("trial"));
      }
      if ((jsonObj.get("trialPeriod") != null && !jsonObj.get("trialPeriod").isJsonNull()) && !jsonObj.get("trialPeriod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `trialPeriod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trialPeriod").toString()));
      }
      // validate the optional field `trialPeriod`
      if (jsonObj.get("trialPeriod") != null && !jsonObj.get("trialPeriod").isJsonNull()) {
        TrialPeriodEnum.validateJsonElement(jsonObj.get("trialPeriod"));
      }
      // validate the optional field `trialEnd`
      if (jsonObj.get("trialEnd") != null && !jsonObj.get("trialEnd").isJsonNull()) {
        SubscriptionCreateTrialEnd.validateJsonElement(jsonObj.get("trialEnd"));
      }
      // validate the optional field `startedAt`
      if (jsonObj.get("startedAt") != null && !jsonObj.get("startedAt").isJsonNull()) {
        SubscriptionCreateTrialEnd.validateJsonElement(jsonObj.get("startedAt"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubscriptionCreate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubscriptionCreate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubscriptionCreate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubscriptionCreate.class));

       return (TypeAdapter<T>) new TypeAdapter<SubscriptionCreate>() {
           @Override
           public void write(JsonWriter out, SubscriptionCreate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubscriptionCreate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubscriptionCreate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubscriptionCreate
   * @throws IOException if the JSON string is invalid with respect to SubscriptionCreate
   */
  public static SubscriptionCreate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubscriptionCreate.class);
  }

  /**
   * Convert an instance of SubscriptionCreate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

