/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.moosyl.model.SubscriptionCreateTrial;
import com.moosyl.model.SubscriptionCreateTrialEnd;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.moosyl.JSON;

/**
 * SubscriptionCreateByExternalUser
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class SubscriptionCreateByExternalUser {
  public static final String SERIALIZED_NAME_EXTERNAL_USER_ID = "externalUserId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_USER_ID)
  @javax.annotation.Nonnull
  private String externalUserId;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  @javax.annotation.Nullable
  private String phone;

  public static final String SERIALIZED_NAME_PRICE_ID = "priceId";
  @SerializedName(SERIALIZED_NAME_PRICE_ID)
  @javax.annotation.Nonnull
  private String priceId;

  public static final String SERIALIZED_NAME_TRIAL = "trial";
  @SerializedName(SERIALIZED_NAME_TRIAL)
  @javax.annotation.Nullable
  private SubscriptionCreateTrial trial;

  /**
   * Gets or Sets trialPeriod
   */
  @JsonAdapter(TrialPeriodEnum.Adapter.class)
  public enum TrialPeriodEnum {
    _1_WEEK("1_week"),
    
    _1_MONTH("1_month"),
    
    _1_YEAR("1_year");

    private String value;

    TrialPeriodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TrialPeriodEnum fromValue(String value) {
      for (TrialPeriodEnum b : TrialPeriodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TrialPeriodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TrialPeriodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TrialPeriodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TrialPeriodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TrialPeriodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TRIAL_PERIOD = "trialPeriod";
  @SerializedName(SERIALIZED_NAME_TRIAL_PERIOD)
  @javax.annotation.Nullable
  private TrialPeriodEnum trialPeriod;

  public static final String SERIALIZED_NAME_TRIAL_END = "trialEnd";
  @SerializedName(SERIALIZED_NAME_TRIAL_END)
  @javax.annotation.Nullable
  private SubscriptionCreateTrialEnd trialEnd;

  public static final String SERIALIZED_NAME_STARTED_AT = "startedAt";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  @javax.annotation.Nullable
  private SubscriptionCreateTrialEnd startedAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private SubscriptionCreateTrialEnd expiresAt;

  public SubscriptionCreateByExternalUser() {
  }

  public SubscriptionCreateByExternalUser externalUserId(@javax.annotation.Nonnull String externalUserId) {
    this.externalUserId = externalUserId;
    return this;
  }

  /**
   * Get externalUserId
   * @return externalUserId
   */
  @javax.annotation.Nonnull
  public String getExternalUserId() {
    return externalUserId;
  }

  public void setExternalUserId(@javax.annotation.Nonnull String externalUserId) {
    this.externalUserId = externalUserId;
  }


  public SubscriptionCreateByExternalUser phone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  public String getPhone() {
    return phone;
  }

  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public SubscriptionCreateByExternalUser priceId(@javax.annotation.Nonnull String priceId) {
    this.priceId = priceId;
    return this;
  }

  /**
   * Get priceId
   * @return priceId
   */
  @javax.annotation.Nonnull
  public String getPriceId() {
    return priceId;
  }

  public void setPriceId(@javax.annotation.Nonnull String priceId) {
    this.priceId = priceId;
  }


  public SubscriptionCreateByExternalUser trial(@javax.annotation.Nullable SubscriptionCreateTrial trial) {
    this.trial = trial;
    return this;
  }

  /**
   * Get trial
   * @return trial
   */
  @javax.annotation.Nullable
  public SubscriptionCreateTrial getTrial() {
    return trial;
  }

  public void setTrial(@javax.annotation.Nullable SubscriptionCreateTrial trial) {
    this.trial = trial;
  }


  public SubscriptionCreateByExternalUser trialPeriod(@javax.annotation.Nullable TrialPeriodEnum trialPeriod) {
    this.trialPeriod = trialPeriod;
    return this;
  }

  /**
   * Get trialPeriod
   * @return trialPeriod
   */
  @javax.annotation.Nullable
  public TrialPeriodEnum getTrialPeriod() {
    return trialPeriod;
  }

  public void setTrialPeriod(@javax.annotation.Nullable TrialPeriodEnum trialPeriod) {
    this.trialPeriod = trialPeriod;
  }


  public SubscriptionCreateByExternalUser trialEnd(@javax.annotation.Nullable SubscriptionCreateTrialEnd trialEnd) {
    this.trialEnd = trialEnd;
    return this;
  }

  /**
   * Get trialEnd
   * @return trialEnd
   */
  @javax.annotation.Nullable
  public SubscriptionCreateTrialEnd getTrialEnd() {
    return trialEnd;
  }

  public void setTrialEnd(@javax.annotation.Nullable SubscriptionCreateTrialEnd trialEnd) {
    this.trialEnd = trialEnd;
  }


  public SubscriptionCreateByExternalUser startedAt(@javax.annotation.Nullable SubscriptionCreateTrialEnd startedAt) {
    this.startedAt = startedAt;
    return this;
  }

  /**
   * Get startedAt
   * @return startedAt
   */
  @javax.annotation.Nullable
  public SubscriptionCreateTrialEnd getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(@javax.annotation.Nullable SubscriptionCreateTrialEnd startedAt) {
    this.startedAt = startedAt;
  }


  public SubscriptionCreateByExternalUser expiresAt(@javax.annotation.Nullable SubscriptionCreateTrialEnd expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public SubscriptionCreateTrialEnd getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable SubscriptionCreateTrialEnd expiresAt) {
    this.expiresAt = expiresAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionCreateByExternalUser subscriptionCreateByExternalUser = (SubscriptionCreateByExternalUser) o;
    return Objects.equals(this.externalUserId, subscriptionCreateByExternalUser.externalUserId) &&
        Objects.equals(this.phone, subscriptionCreateByExternalUser.phone) &&
        Objects.equals(this.priceId, subscriptionCreateByExternalUser.priceId) &&
        Objects.equals(this.trial, subscriptionCreateByExternalUser.trial) &&
        Objects.equals(this.trialPeriod, subscriptionCreateByExternalUser.trialPeriod) &&
        Objects.equals(this.trialEnd, subscriptionCreateByExternalUser.trialEnd) &&
        Objects.equals(this.startedAt, subscriptionCreateByExternalUser.startedAt) &&
        Objects.equals(this.expiresAt, subscriptionCreateByExternalUser.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalUserId, phone, priceId, trial, trialPeriod, trialEnd, startedAt, expiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionCreateByExternalUser {\n");
    sb.append("    externalUserId: ").append(toIndentedString(externalUserId)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    priceId: ").append(toIndentedString(priceId)).append("\n");
    sb.append("    trial: ").append(toIndentedString(trial)).append("\n");
    sb.append("    trialPeriod: ").append(toIndentedString(trialPeriod)).append("\n");
    sb.append("    trialEnd: ").append(toIndentedString(trialEnd)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("externalUserId", "phone", "priceId", "trial", "trialPeriod", "trialEnd", "startedAt", "expiresAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("externalUserId", "priceId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubscriptionCreateByExternalUser
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubscriptionCreateByExternalUser.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SubscriptionCreateByExternalUser is not found in the empty JSON string", SubscriptionCreateByExternalUser.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubscriptionCreateByExternalUser.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SubscriptionCreateByExternalUser` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubscriptionCreateByExternalUser.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("externalUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `externalUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalUserId").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if (!jsonObj.get("priceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `priceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("priceId").toString()));
      }
      // validate the optional field `trial`
      if (jsonObj.get("trial") != null && !jsonObj.get("trial").isJsonNull()) {
        SubscriptionCreateTrial.validateJsonElement(jsonObj.get("trial"));
      }
      if ((jsonObj.get("trialPeriod") != null && !jsonObj.get("trialPeriod").isJsonNull()) && !jsonObj.get("trialPeriod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `trialPeriod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trialPeriod").toString()));
      }
      // validate the optional field `trialPeriod`
      if (jsonObj.get("trialPeriod") != null && !jsonObj.get("trialPeriod").isJsonNull()) {
        TrialPeriodEnum.validateJsonElement(jsonObj.get("trialPeriod"));
      }
      // validate the optional field `trialEnd`
      if (jsonObj.get("trialEnd") != null && !jsonObj.get("trialEnd").isJsonNull()) {
        SubscriptionCreateTrialEnd.validateJsonElement(jsonObj.get("trialEnd"));
      }
      // validate the optional field `startedAt`
      if (jsonObj.get("startedAt") != null && !jsonObj.get("startedAt").isJsonNull()) {
        SubscriptionCreateTrialEnd.validateJsonElement(jsonObj.get("startedAt"));
      }
      // validate the optional field `expiresAt`
      if (jsonObj.get("expiresAt") != null && !jsonObj.get("expiresAt").isJsonNull()) {
        SubscriptionCreateTrialEnd.validateJsonElement(jsonObj.get("expiresAt"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubscriptionCreateByExternalUser.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubscriptionCreateByExternalUser' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubscriptionCreateByExternalUser> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubscriptionCreateByExternalUser.class));

       return (TypeAdapter<T>) new TypeAdapter<SubscriptionCreateByExternalUser>() {
           @Override
           public void write(JsonWriter out, SubscriptionCreateByExternalUser value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubscriptionCreateByExternalUser read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubscriptionCreateByExternalUser given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubscriptionCreateByExternalUser
   * @throws IOException if the JSON string is invalid with respect to SubscriptionCreateByExternalUser
   */
  public static SubscriptionCreateByExternalUser fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubscriptionCreateByExternalUser.class);
  }

  /**
   * Convert an instance of SubscriptionCreateByExternalUser to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

