/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.CheckoutSessionCreate;
import com.moosyl.model.CheckoutSessionCreateBody;
import com.moosyl.model.CheckoutSessionGet;
import com.moosyl.model.CheckoutSessionPayBody;
import com.moosyl.model.CheckoutSessionSelectMethodBody;
import com.moosyl.model.CheckoutSessionSwitchMethod;
import com.moosyl.model.PostCheckoutSessionPublicByIdPay200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CheckoutSessionApi
 */
@Disabled
public class CheckoutSessionApiTest {

    private final CheckoutSessionApi api = new CheckoutSessionApi();

    /**
     * Get public checkout session
     *
     * Get checkout session details without an API key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCheckoutSessionPublicByIdTest() throws ApiException {
        String id = null;
        CheckoutSessionGet response = api.getCheckoutSessionPublicById(id);
        // TODO: test validations
    }

    /**
     * Create checkout session
     *
     * Create a hosted checkout session from paymentRequestId, or from transactionId (optionally creating the payment request when amount is provided).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCheckoutSessionTest() throws ApiException {
        CheckoutSessionCreateBody checkoutSessionCreateBody = null;
        CheckoutSessionCreate response = api.postCheckoutSession(checkoutSessionCreateBody);
        // TODO: test validations
    }

    /**
     * Pay public checkout session
     *
     * Create payment for a checkout session without requiring API key in the client.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCheckoutSessionPublicByIdPayTest() throws ApiException {
        String id = null;
        CheckoutSessionPayBody checkoutSessionPayBody = null;
        PostCheckoutSessionPublicByIdPay200Response response = api.postCheckoutSessionPublicByIdPay(id, checkoutSessionPayBody);
        // TODO: test validations
    }

    /**
     * Switch public checkout method
     *
     * Switch checkout method and cancel the latest pending payment when present.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCheckoutSessionPublicByIdSwitchMethodTest() throws ApiException {
        String id = null;
        CheckoutSessionSelectMethodBody checkoutSessionSelectMethodBody = null;
        CheckoutSessionSwitchMethod response = api.postCheckoutSessionPublicByIdSwitchMethod(id, checkoutSessionSelectMethodBody);
        // TODO: test validations
    }

}
