/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.DeleteConnectRevoke200Response;
import com.moosyl.model.DeleteConnectRevokeRequest;
import com.moosyl.model.PostConnectExchange200Response;
import com.moosyl.model.PostConnectExchangeRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConnectApi
 */
@Disabled
public class ConnectApiTest {

    private final ConnectApi api = new ConnectApi();

    /**
     * Revoke a platform connection
     *
     * Revoke a previously authorized connection between a platform and a Moosyl account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteConnectRevokeTest() throws ApiException {
        DeleteConnectRevokeRequest deleteConnectRevokeRequest = null;
        DeleteConnectRevoke200Response response = api.deleteConnectRevoke(deleteConnectRevokeRequest);
        // TODO: test validations
    }

    /**
     * Exchange authorization code for API credentials
     *
     * Exchange a short-lived authorization code (obtained from the /connect flow) for the user&#39;s publishable key, secret key, and webhook secret. A webhook will be created using the provided endpoints.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postConnectExchangeTest() throws ApiException {
        PostConnectExchangeRequest postConnectExchangeRequest = null;
        PostConnectExchange200Response response = api.postConnectExchange(postConnectExchangeRequest);
        // TODO: test validations
    }

}
