/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.CustomerCreate;
import com.moosyl.model.CustomerGet;
import com.moosyl.model.CustomerList;
import com.moosyl.model.CustomerUpdate;
import com.moosyl.model.GetProductsPageParameter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomersApi
 */
@Disabled
public class CustomersApiTest {

    private final CustomersApi api = new CustomersApi();

    /**
     * List customers or filter by id/external user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCustomersTest() throws ApiException {
        String id = null;
        String externalUserId = null;
        GetProductsPageParameter page = null;
        GetProductsPageParameter limit = null;
        CustomerList response = api.getCustomers(id, externalUserId, page, limit);
        // TODO: test validations
    }

    /**
     * Update customer
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchCustomersByIdTest() throws ApiException {
        String id = null;
        CustomerUpdate customerUpdate = null;
        CustomerGet response = api.patchCustomersById(id, customerUpdate);
        // TODO: test validations
    }

    /**
     * Create customer
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCustomersTest() throws ApiException {
        CustomerCreate customerCreate = null;
        CustomerGet response = api.postCustomers(customerCreate);
        // TODO: test validations
    }

}
