/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.GetProductsPageParameter;
import com.moosyl.model.InvoiceList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoicesApi
 */
@Disabled
public class InvoicesApiTest {

    private final InvoicesApi api = new InvoicesApi();

    /**
     * List invoices or filter by id/external user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInvoicesTest() throws ApiException {
        String id = null;
        String externalUserId = null;
        String subscriptionId = null;
        GetProductsPageParameter page = null;
        GetProductsPageParameter limit = null;
        InvoiceList response = api.getInvoices(id, externalUserId, subscriptionId, page, limit);
        // TODO: test validations
    }

}
