/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.PostMasriviInitiate200Response;
import com.moosyl.model.PostMasriviInitiateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MasriviApi
 */
@Disabled
public class MasriviApiTest {

    private final MasriviApi api = new MasriviApi();

    /**
     * Initiate Masrivi payment
     *
     * Creates a pending payment and returns form data to redirect customer to Masrivi payment page.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postMasriviInitiateTest() throws ApiException {
        PostMasriviInitiateRequest postMasriviInitiateRequest = null;
        PostMasriviInitiate200Response response = api.postMasriviInitiate(postMasriviInitiateRequest);
        // TODO: test validations
    }

}
