/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.PaymentRequestCreate;
import com.moosyl.model.PaymentRequestGet;
import com.moosyl.model.PaymentRequestRefreshStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentRequestApi
 */
@Disabled
public class PaymentRequestApiTest {

    private final PaymentRequestApi api = new PaymentRequestApi();

    /**
     * Get payment request
     *
     * Retrieve a payment request by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentRequestByIdTest() throws ApiException {
        String id = null;
        PaymentRequestGet response = api.getPaymentRequestById(id);
        // TODO: test validations
    }

    /**
     * Get payment request by transaction ID
     *
     * Retrieve a payment request by transaction ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPaymentRequestByTransactionByTransactionIdTest() throws ApiException {
        String transactionId = null;
        PaymentRequestGet response = api.getPaymentRequestByTransactionByTransactionId(transactionId);
        // TODO: test validations
    }

    /**
     * Refresh payment request status
     *
     * Refresh the status of a payment request by transaction ID. Requires secret API key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchPaymentRequestByTransactionIdRefreshStatusTest() throws ApiException {
        String transactionId = null;
        PaymentRequestRefreshStatus response = api.patchPaymentRequestByTransactionIdRefreshStatus(transactionId);
        // TODO: test validations
    }

    /**
     * Create payment request
     *
     * Create a new payment request that can be used to collect payments. Requires secret API key.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postPaymentRequestTest() throws ApiException {
        PaymentRequestCreate paymentRequestCreate = null;
        PaymentRequestGet response = api.postPaymentRequest(paymentRequestCreate);
        // TODO: test validations
    }

}
