/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.PriceCreate;
import com.moosyl.model.PriceGet;
import com.moosyl.model.PriceUpdate;
import com.moosyl.model.Success;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PricesApi
 */
@Disabled
public class PricesApiTest {

    private final PricesApi api = new PricesApi();

    /**
     * Get price
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPricesByIdTest() throws ApiException {
        String id = null;
        PriceGet response = api.getPricesById(id);
        // TODO: test validations
    }

    /**
     * Update price
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchPricesByIdTest() throws ApiException {
        String id = null;
        PriceUpdate priceUpdate = null;
        PriceGet response = api.patchPricesById(id, priceUpdate);
        // TODO: test validations
    }

    /**
     * Archive price
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchPricesByIdArchiveTest() throws ApiException {
        String id = null;
        Success response = api.patchPricesByIdArchive(id);
        // TODO: test validations
    }

    /**
     * Create price
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postPricesTest() throws ApiException {
        PriceCreate priceCreate = null;
        PriceGet response = api.postPrices(priceCreate);
        // TODO: test validations
    }

}
