/*
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania's popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.moosyl.api;

import com.moosyl.ApiException;
import com.moosyl.model.GetProductsPageParameter;
import com.moosyl.model.ProductCreate;
import com.moosyl.model.ProductGet;
import com.moosyl.model.ProductGetWithPrices;
import com.moosyl.model.ProductList;
import com.moosyl.model.ProductUpdate;
import com.moosyl.model.Success;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Disabled
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * List products or filter by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductsTest() throws ApiException {
        String id = null;
        GetProductsPageParameter page = null;
        GetProductsPageParameter limit = null;
        ProductList response = api.getProducts(id, page, limit);
        // TODO: test validations
    }

    /**
     * Get product with prices
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductsByIdTest() throws ApiException {
        String id = null;
        ProductGetWithPrices response = api.getProductsById(id);
        // TODO: test validations
    }

    /**
     * Update product
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchProductsByIdTest() throws ApiException {
        String id = null;
        ProductUpdate productUpdate = null;
        ProductGet response = api.patchProductsById(id, productUpdate);
        // TODO: test validations
    }

    /**
     * Archive product
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchProductsByIdArchiveTest() throws ApiException {
        String id = null;
        Success response = api.patchProductsByIdArchive(id);
        // TODO: test validations
    }

    /**
     * Create product
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postProductsTest() throws ApiException {
        ProductCreate productCreate = null;
        ProductGet response = api.postProducts(productCreate);
        // TODO: test validations
    }

}
